--- #YAML:1.0
name:               Net-SNMPTrapd
version:            0.03
abstract:           Perl implementation of SNMP Trap Listener
author:
    - Michael Vincent <vin at vinsworld dot com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Convert::ASN1:  0.22
    IO::Socket:     ~
    Test::Simple:   ~
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
